// words.js

var words = {

  "走る": {

    "group": "godan",

    "conjugations": {

      "dictionary": "走[はし]る",
      "negative": "走[はし]らない",
      "polite": "走[はし]ります",
      "polite negative": "走[はし]りません",
      "past": "走[はし]った",
      "past negative": "走[はし]らなかった",
      "polite past": "走[はし]りました",
      "polite past negative": "走[はし]りませんでした",
      "te-form": "走[はし]って",
      "te-form negative": ["走[はし]らなくて", "走[はし]らないで"],
      "potential": "走[はし]れる",
      "potential negative": "走[はし]れない",
      "passive": "走[はし]られる",
      "passive negative": "走[はし]られない",
      "causative": "走[はし]らせる",
      "causative negative": "走[はし]らせない",
      "causative passive": "走[はし]らせられる",
      "causative passive negative": "走[はし]らせられない",
      "imperative": "走[はし]れ",
      "imperative negative": "走[はし]るな",
      "progressive": "走[はし]っている",
      "progressive negative": "走[はし]っていない",
      "polite progressive": "走[はし]っています",
      "polite progressive negative": "走[はし]っていません",
      "progressive past": "走[はし]っていた",
      "progressive past negative": "走[はし]っていなかった",
      "polite progressive past": "走[はし]っていました",
      "polite progressive past negative": "走[はし]っていませんでした",
    },
  },

  "死ぬ": {

    "group": "godan",

    "conjugations": {

      "dictionary": "死[し]ぬ",
      "negative": "死[し]なない",
      "polite": "死[し]にます",
      "polite negative": "死[し]にません",
      "past": "死[し]んだ",
      "past negative": "死[し]ななかった",
      "polite past": "死[し]にました",
      "polite past negative": "死[し]にませんでした",
      "te-form": "死[し]んで",
      "te-form negative": ["死[し]ななくて", "死[し]なないで"],
      "potential": "死[し]ねる",
      "potential negative": "死[し]ねない",
      "passive": "死[し]なれる",
      "passive negative": "死[し]なれない",
      "causative": "死[し]なせる",
      "causative negative": "死[し]なせない",
      "causative passive": "死[し]なせられる",
      "causative passive negative": "死[し]なせられない",
      "imperative": "死[し]ね",
      "imperative negative": "死[し]ぬな",
      "progressive": "死[し]んでいる",
      "progressive negative": "死[し]んでいない",
      "polite progressive": "死[し]んでいます",
      "polite progressive negative": "死[し]んでいません",
      "progressive past": "死[し]んでいた",
      "progressive past negative": "死[し]んでいなかった",
      "polite progressive past": "死[し]んでいました",
      "polite progressive past negative": "死[し]んでいませんでした",
    },
  },

  "上げる": {

    "group": "ichidan",

    "conjugations": {

      "dictionary": "上[あ]げる",
      "negative": "上[あ]げない",
      "polite": "上[あ]げます",
      "polite negative": "上[あ]げません",
      "past": "上[あ]げた",
      "past negative": "上[あ]げなかった",
      "polite past": "上[あ]げました",
      "polite past negative": "上[あ]げませんでした",
      "te-form": "上[あ]げて",
      "te-form negative": ["上[あ]げなくて", "上[あ]げないで"],
      "potential": "上[あ]げられる",
      "potential negative": "上[あ]げられない",
      "passive": "上[あ]げられる",
      "passive negative": "上[あ]げられない",
      "causative": "上[あ]げさせる",
      "causative negative": "上[あ]げさせない",
      "causative passive": "上[あ]げさせられる",
      "causative passive negative": "上[あ]げさせられない",
      "imperative": "上[あ]げろ",
      "imperative negative": "上[あ]げるな",
      "progressive": "上[あ]げている",
      "progressive negative": "上[あ]げていない",
      "polite progressive": "上[あ]げています",
      "polite progressive negative": "上[あ]げていません",
      "progressive past": "上[あ]げていた",
      "progressive past negative": "上[あ]げていなかった",
      "polite progressive past": "上[あ]げていました",
      "polite progressive past negative": "上[あ]げていませんでした",
    },
  },

  "上る": {

    "group": "godan",

    "conjugations": {

      "dictionary": "上[のぼ]る",
      "negative": "上[のぼ]らない",
      "polite": "上[のぼ]ります",
      "polite negative": "上[のぼ]りません",
      "past": "上[のぼ]った",
      "past negative": "上[のぼ]らなかった",
      "polite past": "上[のぼ]りました",
      "polite past negative": "上[のぼ]りませんでした",
      "te-form": "上[のぼ]って",
      "te-form negative": ["上[のぼ]らなくて", "上[のぼ]らないで"],
      "potential": "上[のぼ]れる",
      "potential negative": "上[のぼ]れない",
      "passive": "上[のぼ]られる",
      "passive negative": "上[のぼ]られない",
      "causative": "上[のぼ]らせる",
      "causative negative": "上[のぼ]らせない",
      "causative passive": "上[のぼ]らせられる",
      "causative passive negative": "上[のぼ]らせられない",
      "imperative": "上[のぼ]れ",
      "imperative negative": "上[のぼ]るな",
      "progressive": "上[のぼ]っている",
      "progressive negative": "上[のぼ]っていない",
      "polite progressive": "上[のぼ]っています",
      "polite progressive negative": "上[のぼ]っていません",
      "progressive past": "上[のぼ]っていた",
      "progressive past negative": "上[のぼ]っていなかった",
      "polite progressive past": "上[のぼ]っていました",
      "polite progressive past negative": "上[のぼ]っていませんでした",
    },
  },

  "聞く": {

    "group": "godan",

    "conjugations": {

      "dictionary": "聞[き]く",
      "negative": "聞[き]かない",
      "polite": "聞[き]きます",
      "polite negative": "聞[き]きません",
      "past": "聞[き]いた",
      "past negative": "聞[き]かなかった",
      "polite past": "聞[き]きました",
      "polite past negative": "聞[き]きませんでした",
      "te-form": "聞[き]いて",
      "te-form negative": ["聞[き]かなくて", "聞[き]かないで"],
      "potential": "聞[き]ける",
      "potential negative": "聞[き]けない",
      "passive": "聞[き]かれる",
      "passive negative": "聞[き]かれない",
      "causative": "聞[き]かせる",
      "causative negative": "聞[き]かせない",
      "causative passive": "聞[き]かせられる",
      "causative passive negative": "聞[き]かせられない",
      "imperative": "聞[き]け",
      "imperative negative": "聞[き]くな",
      "progressive": "聞[き]いている",
      "progressive negative": "聞[き]いていない",
      "polite progressive": "聞[き]いています",
      "polite progressive negative": "聞[き]いていません",
      "progressive past": "聞[き]いていた",
      "progressive past negative": "聞[き]いていなかった",
      "polite progressive past": "聞[き]いていました",
      "polite progressive past negative": "聞[き]いていませんでした",
    },
  },

  "書く": {

    "group": "godan",

    "conjugations": {

      "dictionary": "書[か]く",
      "negative": "書[か]かない",
      "polite": "書[か]きます",
      "polite negative": "書[か]きません",
      "past": "書[か]いた",
      "past negative": "書[か]かなかった",
      "polite past": "書[か]きました",
      "polite past negative": "書[か]きませんでした",
      "te-form": "書[か]いて",
      "te-form negative": ["書[か]かなくて", "書[か]かないで"],
      "potential": "書[か]ける",
      "potential negative": "書[か]けない",
      "passive": "書[か]かれる",
      "passive negative": "書[か]かれない",
      "causative": "書[か]かせる",
      "causative negative": "書[か]かせない",
      "causative passive": "書[か]かせられる",
      "causative passive negative": "書[か]かせられない",
      "imperative": "書[か]け",
      "imperative negative": "書[か]くな",
      "progressive": "書[か]いている",
      "progressive negative": "書[か]いていない",
      "polite progressive": "書[か]いています",
      "polite progressive negative": "書[か]いていません",
      "progressive past": "書[か]いていた",
      "progressive past negative": "書[か]いていなかった",
      "polite progressive past": "書[か]いていました",
      "polite progressive past negative": "書[か]いていませんでした",
    },
  },

  "消す": {

    "group": "godan",

    "conjugations": {

      "dictionary": "消[け]す",
      "negative": "消[け]さない",
      "polite": "消[け]します",
      "polite negative": "消[け]しません",
      "past": "消[け]した",
      "past negative": "消[け]さなかった",
      "polite past": "消[け]しました",
      "polite past negative": "消[け]しませんでした",
      "te-form": "消[け]して",
      "te-form negative": ["消[け]さなくて", "消[け]さないで"],
      "potential": "消[け]せる",
      "potential negative": "消[け]せない",
      "passive": "消[け]される",
      "passive negative": "消[け]されない",
      "causative": "消[け]させる",
      "causative negative": "消[け]させない",
      "causative passive": "消[け]させられる",
      "causative passive negative": "消[け]させられない",
      "imperative": "消[け]せ",
      "imperative negative": "消[け]すな",
      "progressive": "消[け]している",
      "progressive negative": "消[け]していない",
      "polite progressive": "消[け]しています",
      "polite progressive negative": "消[け]していません",
      "progressive past": "消[け]していた",
      "progressive past negative": "消[け]していなかった",
      "polite progressive past": "消[け]していました",
      "polite progressive past negative": "消[け]していませんでした",
    },
  },

  "着る": {

    "group": "ichidan",

    "conjugations": {

      "dictionary": "着[き]る",
      "negative": "着[き]ない",
      "polite": "着[き]ます",
      "polite negative": "着[き]ません",
      "past": "着[き]た",
      "past negative": "着[き]なかった",
      "polite past": "着[き]ました",
      "polite past negative": "着[き]ませんでした",
      "te-form": "着[き]て",
      "te-form negative": ["着[き]なくて", "着[き]ないで"],
      "potential": "着[き]られる",
      "potential negative": "着[き]られない",
      "passive": "着[き]られる",
      "passive negative": "着[き]られない",
      "causative": "着[き]させる",
      "causative negative": "着[き]させない",
      "causative passive": "着[き]させられる",
      "causative passive negative": "着[き]させられない",
      "imperative": "着[き]ろ",
      "imperative negative": "着[き]るな",
      "progressive": "着[き]ている",
      "progressive negative": "着[き]ていない",
      "polite progressive": "着[き]ています",
      "polite progressive negative": "着[き]ていません",
      "progressive past": "着[き]ていた",
      "progressive past negative": "着[き]ていなかった",
      "polite progressive past": "着[き]ていました",
      "polite progressive past negative": "着[き]ていませんでした",
    },
  },

  "育てる": {

    "group": "ichidan",

    "conjugations": {

      "dictionary": "育[そだ]てる",
      "negative": "育[そだ]てない",
      "polite": "育[そだ]てます",
      "polite negative": "育[そだ]てません",
      "past": "育[そだ]てた",
      "past negative": "育[そだ]てなかった",
      "polite past": "育[そだ]てました",
      "polite past negative": "育[そだ]てませんでした",
      "te-form": "育[そだ]てて",
      "te-form negative": ["育[そだ]てなくて", "育[そだ]てないで"],
      "potential": "育[そだ]てられる",
      "potential negative": "育[そだ]てられない",
      "passive": "育[そだ]てられる",
      "passive negative": "育[そだ]てられない",
      "causative": "育[そだ]てさせる",
      "causative negative": "育[そだ]てさせない",
      "causative passive": "育[そだ]てさせられる",
      "causative passive negative": "育[そだ]てさせられない",
      "imperative": "育[そだ]てろ",
      "imperative negative": "育[そだ]てるな",
      "progressive": "育[そだ]てている",
      "progressive negative": "育[そだ]てていない",
      "polite progressive": "育[そだ]てています",
      "polite progressive negative": "育[そだ]てていません",
      "progressive past": "育[そだ]てていた",
      "progressive past negative": "育[そだ]てていなかった",
      "polite progressive past": "育[そだ]てていました",
      "polite progressive past negative": "育[そだ]てていませんでした",
    },
  },

  "遊ぶ": {

    "group": "godan",

    "conjugations": {

      "dictionary": "遊[あそ]ぶ",
      "negative": "遊[あそ]ばない",
      "polite": "遊[あそ]びます",
      "polite negative": "遊[あそ]びません",
      "past": "遊[あそ]んだ",
      "past negative": "遊[あそ]ばなかった",
      "polite past": "遊[あそ]びました",
      "polite past negative": "遊[あそ]びませんでした",
      "te-form": "遊[あそ]んで",
      "te-form negative": ["遊[あそ]ばなくて", "遊[あそ]ばないで"],
      "potential": "遊[あそ]べる",
      "potential negative": "遊[あそ]べない",
      "passive": "遊[あそ]ばれる",
      "passive negative": "遊[あそ]ばれない",
      "causative": "遊[あそ]ばせる",
      "causative negative": "遊[あそ]ばせない",
      "causative passive": "遊[あそ]ばせられる",
      "causative passive negative": "遊[あそ]ばせられない",
      "imperative": "遊[あそ]べ",
      "imperative negative": "遊[あそ]ぶな",
      "progressive": "遊[あそ]んでいる",
      "progressive negative": "遊[あそ]んでいない",
      "polite progressive": "遊[あそ]んでいます",
      "polite progressive negative": "遊[あそ]んでいません",
      "progressive past": "遊[あそ]んでいた",
      "progressive past negative": "遊[あそ]んでいなかった",
      "polite progressive past": "遊[あそ]んでいました",
      "polite progressive past negative": "遊[あそ]んでいませんでした",
    },
  },

  "褒める": {

    "group": "ichidan",

    "conjugations": {

      "dictionary": "褒[ほ]める",
      "negative": "褒[ほ]めない",
      "polite": "褒[ほ]めます",
      "polite negative": "褒[ほ]めません",
      "past": "褒[ほ]めた",
      "past negative": "褒[ほ]めなかった",
      "polite past": "褒[ほ]めました",
      "polite past negative": "褒[ほ]めませんでした",
      "te-form": "褒[ほ]めて",
      "te-form negative": ["褒[ほ]めなくて", "褒[ほ]めないで"],
      "potential": "褒[ほ]められる",
      "potential negative": "褒[ほ]められない",
      "passive": "褒[ほ]められる",
      "passive negative": "褒[ほ]められない",
      "causative": "褒[ほ]めさせる",
      "causative negative": "褒[ほ]めさせない",
      "causative passive": "褒[ほ]めさせられる",
      "causative passive negative": "褒[ほ]めさせられない",
      "imperative": "褒[ほ]めろ",
      "imperative negative": "褒[ほ]めるな",
      "progressive": "褒[ほ]めている",
      "progressive negative": "褒[ほ]めていない",
      "polite progressive": "褒[ほ]めています",
      "polite progressive negative": "褒[ほ]めていません",
      "progressive past": "褒[ほ]めていた",
      "progressive past negative": "褒[ほ]めていなかった",
      "polite progressive past": "褒[ほ]めていました",
      "polite progressive past negative": "褒[ほ]めていませんでした",
    },
  },

  "学ぶ": {

    "group": "godan",

    "conjugations": {

      "dictionary": "学[まな]ぶ",
      "negative": "学[まな]ばない",
      "polite": "学[まな]びます",
      "polite negative": "学[まな]びません",
      "past": "学[まな]んだ",
      "past negative": "学[まな]ばなかった",
      "polite past": "学[まな]びました",
      "polite past negative": "学[まな]びませんでした",
      "te-form": "学[まな]んで",
      "te-form negative": ["学[まな]ばなくて", "学[まな]ばないで"],
      "potential": "学[まな]べる",
      "potential negative": "学[まな]べない",
      "passive": "学[まな]ばれる",
      "passive negative": "学[まな]ばれない",
      "causative": "学[まな]ばせる",
      "causative negative": "学[まな]ばせない",
      "causative passive": "学[まな]ばせられる",
      "causative passive negative": "学[まな]ばせられない",
      "imperative": "学[まな]べ",
      "imperative negative": "学[まな]ぶな",
      "progressive": "学[まな]んでいる",
      "progressive negative": "学[まな]んでいない",
      "polite progressive": "学[まな]んでいます",
      "polite progressive negative": "学[まな]んでいません",
      "progressive past": "学[まな]んでいた",
      "progressive past negative": "学[まな]んでいなかった",
      "polite progressive past": "学[まな]んでいました",
      "polite progressive past negative": "学[まな]んでいませんでした",
    },
  },

  "喜ぶ": {

    "group": "godan",

    "conjugations": {

      "dictionary": "喜[よろこ]ぶ",
      "negative": "喜[よろこ]ばない",
      "polite": "喜[よろこ]びます",
      "polite negative": "喜[よろこ]びません",
      "past": "喜[よろこ]んだ",
      "past negative": "喜[よろこ]ばなかった",
      "polite past": "喜[よろこ]びました",
      "polite past negative": "喜[よろこ]びませんでした",
      "te-form": "喜[よろこ]んで",
      "te-form negative": ["喜[よろこ]ばなくて", "喜[よろこ]ばないで"],
      "potential": "喜[よろこ]べる",
      "potential negative": "喜[よろこ]べない",
      "passive": "喜[よろこ]ばれる",
      "passive negative": "喜[よろこ]ばれない",
      "causative": "喜[よろこ]ばせる",
      "causative negative": "喜[よろこ]ばせない",
      "causative passive": "喜[よろこ]ばせられる",
      "causative passive negative": "喜[よろこ]ばせられない",
      "imperative": "喜[よろこ]べ",
      "imperative negative": "喜[よろこ]ぶな",
      "progressive": "喜[よろこ]んでいる",
      "progressive negative": "喜[よろこ]んでいない",
      "polite progressive": "喜[よろこ]んでいます",
      "polite progressive negative": "喜[よろこ]んでいません",
      "progressive past": "喜[よろこ]んでいた",
      "progressive past negative": "喜[よろこ]んでいなかった",
      "polite progressive past": "喜[よろこ]んでいました",
      "polite progressive past negative": "喜[よろこ]んでいませんでした",
    },
  },

  "泳ぐ": {

    "group": "godan",

    "conjugations": {

      "dictionary": "泳[およ]ぐ",
      "negative": "泳[およ]がない",
      "polite": "泳[およ]ぎます",
      "polite negative": "泳[およ]ぎません",
      "past": "泳[およ]いだ",
      "past negative": "泳[およ]がなかった",
      "polite past": "泳[およ]ぎました",
      "polite past negative": "泳[およ]ぎませんでした",
      "te-form": "泳[およ]いで",
      "te-form negative": ["泳[およ]がなくて", "泳[およ]がないで"],
      "potential": "泳[およ]げる",
      "potential negative": "泳[およ]げない",
      "passive": "泳[およ]がれる",
      "passive negative": "泳[およ]がれない",
      "causative": "泳[およ]がせる",
      "causative negative": "泳[およ]がせない",
      "causative passive": "泳[およ]がせられる",
      "causative passive negative": "泳[およ]がせられない",
      "imperative": "泳[およ]げ",
      "imperative negative": "泳[およ]ぐな",
      "progressive": "泳[およ]いでいる",
      "progressive negative": "泳[およ]いでいない",
      "polite progressive": "泳[およ]いでいます",
      "polite progressive negative": "泳[およ]いでいません",
      "progressive past": "泳[およ]いでいた",
      "progressive past negative": "泳[およ]いでいなかった",
      "polite progressive past": "泳[およ]いでいました",
      "polite progressive past negative": "泳[およ]いでいませんでした",
    },
  },

  "注ぐ": {

    "group": "godan",

    "conjugations": {

      "dictionary": "注[そそ]ぐ",
      "negative": "注[そそ]がない",
      "polite": "注[そそ]ぎます",
      "polite negative": "注[そそ]ぎません",
      "past": "注[そそ]いだ",
      "past negative": "注[そそ]がなかった",
      "polite past": "注[そそ]ぎました",
      "polite past negative": "注[そそ]ぎませんでした",
      "te-form": "注[そそ]いで",
      "te-form negative": ["注[そそ]がなくて", "注[そそ]がないで"],
      "potential": "注[そそ]げる",
      "potential negative": "注[そそ]げない",
      "passive": "注[そそ]がれる",
      "passive negative": "注[そそ]がれない",
      "causative": "注[そそ]がせる",
      "causative negative": "注[そそ]がせない",
      "causative passive": "注[そそ]がせられる",
      "causative passive negative": "注[そそ]がせられない",
      "imperative": "注[そそ]げ",
      "imperative negative": "注[そそ]ぐな",
      "progressive": "注[そそ]いでいる",
      "progressive negative": "注[そそ]いでいない",
      "polite progressive": "注[そそ]いでいます",
      "polite progressive negative": "注[そそ]いでいません",
      "progressive past": "注[そそ]いでいた",
      "progressive past negative": "注[そそ]いでいなかった",
      "polite progressive past": "注[そそ]いでいました",
      "polite progressive past negative": "注[そそ]いでいませんでした",
    },
  },

  "急ぐ": {

    "group": "godan",

    "conjugations": {

      "dictionary": "急[いそ]ぐ",
      "negative": "急[いそ]がない",
      "polite": "急[いそ]ぎます",
      "polite negative": "急[いそ]ぎません",
      "past": "急[いそ]いだ",
      "past negative": "急[いそ]がなかった",
      "polite past": "急[いそ]ぎました",
      "polite past negative": "急[いそ]ぎませんでした",
      "te-form": "急[いそ]いで",
      "te-form negative": ["急[いそ]がなくて", "急[いそ]がないで"],
      "potential": "急[いそ]げる",
      "potential negative": "急[いそ]げない",
      "passive": "急[いそ]がれる",
      "passive negative": "急[いそ]がれない",
      "causative": "急[いそ]がせる",
      "causative negative": "急[いそ]がせない",
      "causative passive": "急[いそ]がせられる",
      "causative passive negative": "急[いそ]がせられない",
      "imperative": "急[いそ]げ",
      "imperative negative": "急[いそ]ぐな",
      "progressive": "急[いそ]いでいる",
      "progressive negative": "急[いそ]いでいない",
      "polite progressive": "急[いそ]いでいます",
      "polite progressive negative": "急[いそ]いでいません",
      "progressive past": "急[いそ]いでいた",
      "progressive past negative": "急[いそ]いでいなかった",
      "polite progressive past": "急[いそ]いでいました",
      "polite progressive past negative": "急[いそ]いでいませんでした",
    },
  },

  "立つ": {

    "group": "godan",

    "conjugations": {

      "dictionary": "立[た]つ",
      "negative": "立[た]たない",
      "polite": "立[た]ちます",
      "polite negative": "立[た]ちません",
      "past": "立[た]った",
      "past negative": "立[た]たなかった",
      "polite past": "立[た]ちました",
      "polite past negative": "立[た]ちませんでした",
      "te-form": "立[た]って",
      "te-form negative": ["立[た]たなくて", "立[た]たないで"],
      "potential": "立[た]てる",
      "potential negative": "立[た]てない",
      "passive": "立[た]たれる",
      "passive negative": "立[た]たれない",
      "causative": "立[た]たせる",
      "causative negative": "立[た]たせない",
      "causative passive": "立[た]たせられる",
      "causative passive negative": "立[た]たせられない",
      "imperative": "立[た]て",
      "imperative negative": "立[た]つな",
      "progressive": "立[た]っている",
      "progressive negative": "立[た]っていない",
      "polite progressive": "立[た]っています",
      "polite progressive negative": "立[た]っていません",
      "progressive past": "立[た]っていた",
      "progressive past negative": "立[た]っていなかった",
      "polite progressive past": "立[た]っていました",
      "polite progressive past negative": "立[た]っていませんでした",
    },
  },

  "打つ": {

    "group": "godan",

    "conjugations": {

      "dictionary": "打[う]つ",
      "negative": "打[う]たない",
      "polite": "打[う]ちます",
      "polite negative": "打[う]ちません",
      "past": "打[う]った",
      "past negative": "打[う]たなかった",
      "polite past": "打[う]ちました",
      "polite past negative": "打[う]ちませんでした",
      "te-form": "打[う]って",
      "te-form negative": ["打[う]たなくて", "打[う]たないで"],
      "potential": "打[う]てる",
      "potential negative": "打[う]てない",
      "passive": "打[う]たれる",
      "passive negative": "打[う]たれない",
      "causative": "打[う]たせる",
      "causative negative": "打[う]たせない",
      "causative passive": "打[う]たせられる",
      "causative passive negative": "打[う]たせられない",
      "imperative": "打[う]て",
      "imperative negative": "打[う]つな",
      "progressive": "打[う]っている",
      "progressive negative": "打[う]っていない",
      "polite progressive": "打[う]っています",
      "polite progressive negative": "打[う]っていません",
      "progressive past": "打[う]っていた",
      "progressive past negative": "打[う]っていなかった",
      "polite progressive past": "打[う]っていました",
      "polite progressive past negative": "打[う]っていませんでした",
    },
  },

  "待つ": {

    "group": "godan",

    "conjugations": {

      "dictionary": "待[ま]つ",
      "negative": "待[ま]たない",
      "polite": "待[ま]ちます",
      "polite negative": "待[ま]ちません",
      "past": "待[ま]った",
      "past negative": "待[ま]たなかった",
      "polite past": "待[ま]ちました",
      "polite past negative": "待[ま]ちませんでした",
      "te-form": "待[ま]って",
      "te-form negative": ["待[ま]たなくて", "待[ま]たないで"],
      "potential": "待[ま]てる",
      "potential negative": "待[ま]てない",
      "passive": "待[ま]たれる",
      "passive negative": "待[ま]たれない",
      "causative": "待[ま]たせる",
      "causative negative": "待[ま]たせない",
      "causative passive": "待[ま]たせられる",
      "causative passive negative": "待[ま]たせられない",
      "imperative": "待[ま]て",
      "imperative negative": "待[ま]つな",
      "progressive": "待[ま]っている",
      "progressive negative": "待[ま]っていない",
      "polite progressive": "待[ま]っています",
      "polite progressive negative": "待[ま]っていません",
      "progressive past": "待[ま]っていた",
      "progressive past negative": "待[ま]っていなかった",
      "polite progressive past": "待[ま]っていました",
      "polite progressive past negative": "待[ま]っていませんでした",
    },
  },

  "持つ": {

    "group": "godan",

    "conjugations": {

      "dictionary": "持[も]つ",
      "negative": "持[も]たない",
      "polite": "持[も]ちます",
      "polite negative": "持[も]ちません",
      "past": "持[も]った",
      "past negative": "持[も]たなかった",
      "polite past": "持[も]ちました",
      "polite past negative": "持[も]ちませんでした",
      "te-form": "持[も]って",
      "te-form negative": ["持[も]たなくて", "持[も]たないで"],
      "potential": "持[も]てる",
      "potential negative": "持[も]てない",
      "passive": "持[も]たれる",
      "passive negative": "持[も]たれない",
      "causative": "持[も]たせる",
      "causative negative": "持[も]たせない",
      "causative passive": "持[も]たせられる",
      "causative passive negative": "持[も]たせられない",
      "imperative": "持[も]て",
      "imperative negative": "持[も]つな",
      "progressive": "持[も]っている",
      "progressive negative": "持[も]っていない",
      "polite progressive": "持[も]っています",
      "polite progressive negative": "持[も]っていません",
      "progressive past": "持[も]っていた",
      "progressive past negative": "持[も]っていなかった",
      "polite progressive past": "持[も]っていました",
      "polite progressive past negative": "持[も]っていませんでした",
    },
  },

  "行く": {

    "group": "iku",

    "conjugations": {

      "dictionary": "行[い]く",
      "negative": "行[い]かない",
      "polite": "行[い]きます",
      "polite negative": "行[い]きません",
      "past": "行[い]った",
      "past negative": "行[い]かなかった",
      "polite past": "行[い]きました",
      "polite past negative": "行[い]きませんでした",
      "te-form": "行[い]って",
      "te-form negative": ["行[い]かなくて", "行[い]かないで"],
      "potential": "行[い]ける",
      "potential negative": "行[い]けない",
      "imperative": "行[い]け",
      "imperative negative": "行[い]くな",
      "passive": "行[い]かれる",
      "passive negative": "行[い]かれない",
      "causative": "行[い]かせる",
      "causative negative": "行[い]かせない",
      "causative passive": "行[い]かせられる",
      "causative passive negative": "行[い]かせられない",
      "progressive": "行[い]っている",
      "progressive negative": "行[い]っていない",
      "polite progressive": "行[い]っています",
      "polite progressive negative": "行[い]っていません",
      "progressive past": "行[い]っていた",
      "progressive past negative": "行[い]っていなかった",
      "polite progressive past": "行[い]っていました",
      "polite progressive past negative": "行[い]っていませんでした",
    },
  },

  "飲む": {

    "group": "godan",

    "conjugations": {

      "dictionary": "飲[の]む",
      "negative": "飲[の]まない",
      "polite": "飲[の]みます",
      "polite negative": "飲[の]みません",
      "past": "飲[の]んだ",
      "past negative": "飲[の]まなかった",
      "polite past": "飲[の]みました",
      "polite past negative": "飲[の]みませんでした",
      "te-form": "飲[の]んで",
      "te-form negative": ["飲[の]まなくて", "飲[の]まないで"],
      "potential": "飲[の]める",
      "potential negative": "飲[の]めない",
      "imperative": "飲[の]め",
      "imperative negative": "飲[の]むな",
      "passive": "飲[の]まれる",
      "passive negative": "飲[の]まれない",
      "causative": "飲[の]ませる",
      "causative negative": "飲[の]ませない",
      "causative passive": "飲[の]ませられる",
      "causative passive negative": "飲[の]ませられない",
      "progressive": "飲[の]んでいる",
      "progressive negative": "飲[の]んでいない",
      "polite progressive": "飲[の]んでいます",
      "polite progressive negative": "飲[の]んでいません",
      "progressive past": "飲[の]んでいた",
      "progressive past negative": "飲[の]んでいなかった",
      "polite progressive past": "飲[の]んでいました",
      "polite progressive past negative": "飲[の]んでいませんでした",
    },
  },

  "作る": {

    "group": "godan",

    "conjugations": {

      "dictionary": "作[つく]る",
      "negative": "作[つく]らない",
      "polite": "作[つく]ります",
      "polite negative": "作[つく]りません",
      "past": "作[つく]った",
      "past negative": "作[つく]らなかった",
      "polite past": "作[つく]りました",
      "polite past negative": "作[つく]りませんでした",
      "te-form": "作[つく]って",
      "te-form negative": ["作[つく]らなくて", "作[つく]らないで"],
      "potential": "作[つく]れる",
      "potential negative": "作[つく]れない",
      "imperative": "作[つく]れ",
      "imperative negative": "作[つく]るな",
      "passive": "作[つく]られる",
      "passive negative": "作[つく]られない",
      "causative": "作[つく]らせる",
      "causative negative": "作[つく]らせない",
      "causative passive": "作[つく]らせられる",
      "causative passive negative": "作[つく]らせられない",
      "progressive": "作[つく]っている",
      "progressive negative": "作[つく]っていない",
      "polite progressive": "作[つく]っています",
      "polite progressive negative": "作[つく]っていません",
      "progressive past": "作[つく]っていた",
      "progressive past negative": "作[つく]っていなかった",
      "polite progressive past": "作[つく]っていました",
      "polite progressive past negative": "作[つく]っていませんでした",
    },
  },

  "買い戻す": {

    "group": "godan",

    "conjugations": {

      "dictionary": "買[か]い戻[もど]す",
      "negative": "買[か]い戻[もど]さない",
      "polite": "買[か]い戻[もど]します",
      "polite negative": "買[か]い戻[もど]しません",
      "past": "買[か]い戻[もど]した",
      "past negative": "買[か]い戻[もど]さなかった",
      "polite past": "買[か]い戻[もど]しました",
      "polite past negative": "買[か]い戻[もど]しませんでした",
      "te-form": "買[か]い戻[もど]して",
      "te-form negative": ["買[か]い戻[もど]さなくて", "買[か]い戻[もど]さないで"],
      "potential": "買[か]い戻[もど]せる",
      "potential negative": "買[か]い戻[もど]せない",
      "imperative": "買[か]い戻[もど]せ",
      "imperative negative": "買[か]い戻[もど]すな",
      "passive": "買[か]い戻[もど]される",
      "passive negative": "買[か]い戻[もど]されない",
      "causative": "買[か]い戻[もど]させる",
      "causative negative": "買[か]い戻[もど]させない",
      "causative passive": "買[か]い戻[もど]させられる",
      "causative passive negative": "買[か]い戻[もど]させられない",
      "progressive": "買[か]い戻[もど]している",
      "progressive negative": "買[か]い戻[もど]していない",
      "polite progressive": "買[か]い戻[もど]しています",
      "polite progressive negative": "買[か]い戻[もど]していません",
      "progressive past": "買[か]い戻[もど]していた",
      "progressive past negative": "買[か]い戻[もど]していなかった",
      "polite progressive past": "買[か]い戻[もど]していました",
      "polite progressive past negative": "買[か]い戻[もど]していませんでした",
    },
  },

  "見る": {

    "group": "ichidan",

    "conjugations": {

      "dictionary": "見[み]る",
      "negative": "見[み]ない",
      "polite": "見[み]ます",
      "polite negative": "見[み]ません",
      "past": "見[み]た",
      "past negative": "見[み]なかった",
      "polite past": "見[み]ました",
      "polite past negative": "見[み]ませんでした",
      "te-form": "見[み]て",
      "te-form negative": ["見[み]なくて", "見[み]ないで"],
      "potential": "見[み]られる",
      "potential negative": "見[み]られない",
      "imperative": "見[み]ろ",
      "imperative negative": "見[み]るな",
      "passive": "見[み]られる",
      "passive negative": "見[み]られない",
      "causative": "見[み]させる",
      "causative negative": "見[み]させない",
      "causative passive": "見[み]させられる",
      "causative passive negative": "見[み]させられない",
      "progressive": "見[み]ている",
      "progressive negative": "見[み]ていない",
      "polite progressive": "見[み]ています",
      "polite progressive negative": "見[み]ていません",
      "progressive past": "見[み]ていた",
      "progressive past negative": "見[み]ていなかった",
      "polite progressive past": "見[み]ていました",
      "polite progressive past negative": "見[み]ていませんでした",
    },
  },

  "食べる": {

    "group": "ichidan",

    "conjugations": {

      "dictionary": "食[た]べる",
      "negative": "食[た]べない",
      "polite": "食[た]べます",
      "polite negative": "食[た]べません",
      "past": "食[た]べた",
      "past negative": "食[た]べなかった",
      "polite past": "食[た]べました",
      "polite past negative": "食[た]べませんでした",
      "te-form": "食[た]べて",
      "te-form negative": ["食[た]べなくて", "食[た]べないで"],
      "potential": "食[た]べられる",
      "potential negative": "食[た]べられない",
      "imperative": "食[た]べろ",
      "imperative negative": "食[た]べるな",
      "passive": "食[た]べられる",
      "passive negative": "食[た]べられない",
      "causative": "食[た]べさせる",
      "causative negative": "食[た]べさせない",
      "causative passive": "食[た]べさせられる",
      "causative passive negative": "食[た]べさせられない",
      "progressive": "食[た]べている",
      "progressive negative": "食[た]べていない",
      "polite progressive": "食[た]べています",
      "polite progressive negative": "食[た]べていません",
      "progressive past": "食[た]べていた",
      "progressive past negative": "食[た]べていなかった",
      "polite progressive past": "食[た]べていました",
      "polite progressive past negative": "食[た]べていませんでした",
    },
  },

  "起きる": {

    "group": "ichidan",

    "conjugations": {

      "dictionary": "起[お]きる",
      "negative": "起[お]きない",
      "polite": "起[お]きます",
      "polite negative": "起[お]きません",
      "past": "起[お]きた",
      "past negative": "起[お]きなかった",
      "polite past": "起[お]きました",
      "polite past negative": "起[お]きませんでした",
      "te-form": "起[お]きて",
      "te-form negative": ["起[お]きなくて", "起[お]きないで"],
      "potential": "起[お]きられる",
      "potential negative": "起[お]きられない",
      "imperative": "起[お]きろ",
      "imperative negative": "起[お]きるな",
      "passive": "起[お]きられる",
      "passive negative": "起[お]きられない",
      "causative": "起[お]きさせる",
      "causative negative": "起[お]きさせない",
      "causative passive": "起[お]きさせられる",
      "causative passive negative": "起[お]きさせられない",
      "progressive": "起[お]きている",
      "progressive negative": "起[お]きていない",
      "polite progressive": "起[お]きています",
      "polite progressive negative": "起[お]きていません",
      "progressive past": "起[お]きていた",
      "progressive past negative": "起[お]きていなかった",
      "polite progressive past": "起[お]きていました",
      "polite progressive past negative": "起[お]きていませんでした",
    },
  },

  "買い換える": {

    "group": "ichidan",

    "conjugations": {

      "dictionary": "買[か]い換[か]える",
      "negative": "買[か]い換[か]えない",
      "polite": "買[か]い換[か]えます",
      "polite negative": "買[か]い換[か]えません",
      "past": "買[か]い換[か]えた",
      "past negative": "買[か]い換[か]えなかった",
      "polite past": "買[か]い換[か]えました",
      "polite past negative": "買[か]い換[か]えませんでした",
      "te-form": "買[か]い換[か]えて",
      "te-form negative": ["買[か]い換[か]えなくて", "買[か]い換[か]えないで"],
      "potential": "買[か]い換[か]えられる",
      "potential negative": "買[か]い換[か]えられない",
      "imperative": "買[か]い換[か]えろ",
      "imperative negative": "買[か]い換[か]えるな",
      "passive": "買[か]い換[か]えられる",
      "passive negative": "買[か]い換[か]えられない",
      "causative": "買[か]い換[か]えさせる",
      "causative negative": "買[か]い換[か]えさせない",
      "causative passive": "買[か]い換[か]えさせられる",
      "causative passive negative": "買[か]い換[か]えさせられない",
      "progressive": "買[か]い換[か]えている",
      "progressive negative": "買[か]い換[か]えていない",
      "polite progressive": "買[か]い換[か]えています",
      "polite progressive negative": "買[か]い換[か]えていません",
      "progressive past": "買[か]い換[か]えていた",
      "progressive past negative": "買[か]い換[か]えていなかった",
      "polite progressive past": "買[か]い換[か]えていました",
      "polite progressive past negative": "買[か]い換[か]えていませんでした",
    },
  },

  "来る": {

    "group": "kuru",

    "conjugations": {

      "dictionary": "来[く]る",
      "negative": "来[こ]ない",
      "polite": "来[き]ます",
      "polite negative": "来[き]ません",
      "past": "来[き]た",
      "past negative": "来[こ]なかった",
      "polite past": "来[き]ました",
      "polite past negative": "来[き]ませんでした",
      "te-form": "来[き]て",
      "te-form negative": ["来[こ]なくて", "来[こ]ないで"],
      "potential": "来[こ]られる",
      "potential negative": "来[こ]られない",
      "imperative": "来[こ]い",
      "imperative negative": "来[く]るな",
      "passive": "来[こ]られる",
      "passive negative": "来[こ]られない",
      "causative": "来[こ]させる",
      "causative negative": "来[こ]させない",
      "causative passive": "来[こ]させられる",
      "causative passive negative": "来[こ]させられない",
      "progressive": "来[き]ている",
      "progressive negative": "来[き]ていない",
      "polite progressive": "来[き]ています",
      "polite progressive negative": "来[き]ていません",
      "progressive past": "来[き]ていた",
      "progressive past negative": "来[き]ていなかった",
      "polite progressive past": "来[き]ていました",
      "polite progressive past negative": "来[き]ていませんでした",
    },
  },

  "する": {

    "group": "suru",

    "conjugations": {

      "dictionary": "する",
      "negative": "しない",
      "polite": "します",
      "polite negative": "しません",
      "past": "した",
      "past negative": "しなかった",
      "polite past": "しました",
      "polite past negative": "しませんでした",
      "te-form": "して",
      "te-form negative": ["しなくて", "しないで"],
      "imperative": "しろ",
      "imperative negative": "さるな",
      "progressive": "している",
      "progressive negative": "していない",
      "polite progressive": "しています",
      "polite progressive negative": "していません",
      "progressive past": "していた",
      "progressive past negative": "していなかった",
      "polite progressive past": "していました",
      "polite progressive past negative": "していませんでした",
    },
  },

  "勉強する": {

    "group": "suru",

    "conjugations": {

      "dictionary": "勉[べん]強[きょう]する",
      "negative": "勉[べん]強[きょう]しない",
      "polite": "勉[べん]強[きょう]します",
      "polite negative": "勉[べん]強[きょう]しません",
      "past": "勉[べん]強[きょう]した",
      "past negative": "勉[べん]強[きょう]しなかった",
      "polite past": "勉[べん]強[きょう]しました",
      "polite past negative": "勉[べん]強[きょう]しませんでした",
      "te-form": "勉[べん]強[きょう]して",
      "te-form negative": ["勉[べん]強[きょう]しなくて", "勉[べん]強[きょう]しないで"],
      "imperative": "勉[べん]強[きょう]しろ",
      "imperative negative": "勉[べん]強[きょう]さるな",
      "progressive": "勉[べん]強[きょう]している",
      "progressive negative": "勉[べん]強[きょう]していない",
      "polite progressive": "勉[べん]強[きょう]しています",
      "polite progressive negative": "勉[べん]強[きょう]していません",
      "progressive past": "勉[べん]強[きょう]していた",
      "progressive past negative": "勉[べん]強[きょう]していなかった",
      "polite progressive past": "勉[べん]強[きょう]していました",
      "polite progressive past negative": "勉[べん]強[きょう]していませんでした",
    },
  },

  "電話する": {

    "group": "suru",

    "conjugations": {

      "dictionary": "電[でん]話[わ]する",
      "negative": "電[でん]話[わ]しない",
      "polite": "電[でん]話[わ]します",
      "polite negative": "電[でん]話[わ]しません",
      "past": "電[でん]話[わ]した",
      "past negative": "電[でん]話[わ]しなかった",
      "polite past": "電[でん]話[わ]しました",
      "polite past negative": "電[でん]話[わ]しませんでした",
      "te-form": "電[でん]話[わ]して",
      "te-form negative": ["電[でん]話[わ]しなくて", "電[でん]話[わ]しないで"],
      "imperative": "電[でん]話[わ]しろ",
      "imperative negative": "電[でん]話[わ]さるな",
      "progressive": "電[でん]話[わ]している",
      "progressive negative": "電[でん]話[わ]していない",
      "polite progressive": "電[でん]話[わ]しています",
      "polite progressive negative": "電[でん]話[わ]していません",
      "progressive past": "電[でん]話[わ]していた",
      "progressive past negative": "電[でん]話[わ]していなかった",
      "polite progressive past": "電[でん]話[わ]していました",
      "polite progressive past negative": "電[でん]話[わ]していませんでした",
    },
  },

  "開発する": {

    "group": "suru",

    "conjugations": {

      "dictionary": "開[かい]発[はつ]する",
      "negative": "開[かい]発[はつ]しない",
      "polite": "開[かい]発[はつ]します",
      "polite negative": "開[かい]発[はつ]しません",
      "past": "開[かい]発[はつ]した",
      "past negative": "開[かい]発[はつ]しなかった",
      "polite past": "開[かい]発[はつ]しました",
      "polite past negative": "開[かい]発[はつ]しませんでした",
      "te-form": "開[かい]発[はつ]して",
      "te-form negative": ["開[かい]発[はつ]しなくて", "開[かい]発[はつ]しないで"],
      "imperative": "開[かい]発[はつ]しろ",
      "imperative negative": "開[かい]発[はつ]さるな",
      "progressive": "開[かい]発[はつ]している",
      "progressive negative": "開[かい]発[はつ]していない",
      "polite progressive": "開[かい]発[はつ]しています",
      "polite progressive negative": "開[かい]発[はつ]していません",
      "progressive past": "開[かい]発[はつ]していた",
      "progressive past negative": "開[かい]発[はつ]していなかった",
      "polite progressive past": "開[かい]発[はつ]していました",
      "polite progressive past negative": "開[かい]発[はつ]していませんでした",
    },
  },

  "計算する": {

    "group": "suru",

    "conjugations": {

      "dictionary": "計[けい]算[さん]する",
      "negative": "計[けい]算[さん]しない",
      "polite": "計[けい]算[さん]します",
      "polite negative": "計[けい]算[さん]しません",
      "past": "計[けい]算[さん]した",
      "past negative": "計[けい]算[さん]しなかった",
      "polite past": "計[けい]算[さん]しました",
      "polite past negative": "計[けい]算[さん]しませんでした",
      "te-form": "計[けい]算[さん]して",
      "te-form negative": ["計[けい]算[さん]しなくて", "計[けい]算[さん]しないで"],
      "imperative": "計[けい]算[さん]しろ",
      "imperative negative": "計[けい]算[さん]さるな",
      "progressive": "計[けい]算[さん]している",
      "progressive negative": "計[けい]算[さん]していない",
      "polite progressive": "計[けい]算[さん]しています",
      "polite progressive negative": "計[けい]算[さん]していません",
      "progressive past": "計[けい]算[さん]していた",
      "progressive past negative": "計[けい]算[さん]していなかった",
      "polite progressive past": "計[けい]算[さん]していました",
      "polite progressive past negative": "計[けい]算[さん]していませんでした",
    },
  },

  "読む": {

    "group": "godan",

    "conjugations": {

      "dictionary": "読[よ]む",
      "negative": "読[よ]まない",
      "polite": "読[よ]みます",
      "polite negative": "読[よ]みません",
      "past": "読[よ]んだ",
      "past negative": "読[よ]まなかった",
      "polite past": "読[よ]みました",
      "polite past negative": "読[よ]みませんでした",
      "te-form": "読[よ]んで",
      "te-form negative": ["読[よ]まなくて", "読[よ]まないで"],
      "potential": "読[よ]める",
      "potential negative": "読[よ]めない",
      "imperative": "読[よ]め",
      "imperative negative": "読[よ]むな",
      "passive": "読[よ]まれる",
      "passive negative": "読[よ]まれない",
      "causative": "読[よ]ませる",
      "causative negative": "読[よ]ませない",
      "causative passive": "読[よ]ませられる",
      "causative passive negative": "読[よ]ませられない",
      "progressive": "読[よ]んでいる",
      "progressive negative": "読[よ]んでいない",
      "polite progressive": "読[よ]んでいます",
      "polite progressive negative": "読[よ]んでいません",
      "progressive past": "読[よ]んでいた",
      "progressive past negative": "読[よ]んでいなかった",
      "polite progressive past": "読[よ]んでいました",
      "polite progressive past negative": "読[よ]んでいませんでした",
    },
  },

  "思う": {

    "group": "godan",

    "conjugations": {

      "dictionary": "思[おも]う",
      "negative": "思[おも]わない",
      "polite": "思[おも]います",
      "polite negative": "思[おも]いません",
      "past": "思[おも]った",
      "past negative": "思[おも]わなかった",
      "polite past": "思[おも]いました",
      "polite past negative": "思[おも]いませんでした",
      "te-form": "思[おも]って",
      "te-form negative": ["思[おも]わなくて", "思[おも]わないで"],
      "potential": "思[おも]える",
      "potential negative": "思[おも]えない",
      "imperative": "思[おも]え",
      "imperative negative": "思[おも]うな",
      "passive": "思[おも]われる",
      "passive negative": "思[おも]われない",
      "causative": "思[おも]わせる",
      "causative negative": "思[おも]わせない",
      "causative passive": "思[おも]わせられる",
      "causative passive negative": "思[おも]わせられない",
      "progressive": "思[おも]っている",
      "progressive negative": "思[おも]っていない",
      "polite progressive": "思[おも]っています",
      "polite progressive negative": "思[おも]っていません",
      "progressive past": "思[おも]っていた",
      "progressive past negative": "思[おも]っていなかった",
      "polite progressive past": "思[おも]っていました",
      "polite progressive past negative": "思[おも]っていませんでした",
    },
  },

  "買い与える": {

    "group": "ichidan",

    "conjugations": {

      "dictionary": "買[か]い与[あた]える",
      "negative": "買[か]い与[あた]えない",
      "polite": "買[か]い与[あた]えます",
      "polite negative": "買[か]い与[あた]えません",
      "past": "買[か]い与[あた]えた",
      "past negative": "買[か]い与[あた]えなかった",
      "polite past": "買[か]い与[あた]えました",
      "polite past negative": "買[か]い与[あた]えませんでした",
      "te-form": "買[か]い与[あた]えて",
      "te-form negative": ["買[か]い与[あた]えなくて", "買[か]い与[あた]えないで"],
      "potential": "買[か]い与[あた]えられる",
      "potential negative": "買[か]い与[あた]えられない",
      "imperative": "買[か]い与[あた]えろ",
      "imperative negative": "買[か]い与[あた]えるな",
      "passive": "買[か]い与[あた]えられる",
      "passive negative": "買[か]い与[あた]えられない",
      "causative": "買[か]い与[あた]えさせる",
      "causative negative": "買[か]い与[あた]えさせない",
      "causative passive": "買[か]い与[あた]えさせられる",
      "causative passive negative": "買[か]い与[あた]えさせられない",
      "progressive": "買[か]い与[あた]えている",
      "progressive negative": "買[か]い与[あた]えていない",
      "polite progressive": "買[か]い与[あた]えています",
      "polite progressive negative": "買[か]い与[あた]えていません",
      "progressive past": "買[か]い与[あた]えていた",
      "progressive past negative": "買[か]い与[あた]えていなかった",
      "polite progressive past": "買[か]い与[あた]えていました",
      "polite progressive past negative": "買[か]い与[あた]えていませんでした",
    },
  },

  "座る": {

    "group": "godan",

    "conjugations": {

      "dictionary": "座[すわ]る",
      "negative": "座[すわ]らない",
      "polite": "座[すわ]ります",
      "polite negative": "座[すわ]りません",
      "past": "座[すわ]った",
      "past negative": "座[すわ]らなかった",
      "polite past": "座[すわ]りました",
      "polite past negative": "座[すわ]りませんでした",
      "te-form": "座[すわ]って",
      "te-form negative": ["座[すわ]らなくて", "座[すわ]らないで"],
      "potential": "座[すわ]れる",
      "potential negative": "座[すわ]れない",
      "imperative": "座[すわ]れ",
      "imperative negative": "座[すわ]るな",
      "passive": "座[すわ]られる",
      "passive negative": "座[すわ]られない",
      "causative": "座[すわ]らせる",
      "causative negative": "座[すわ]らせない",
      "causative passive": "座[すわ]らせられる",
      "causative passive negative": "座[すわ]らせられない",
      "progressive": "座[すわ]っている",
      "progressive negative": "座[すわ]っていない",
      "polite progressive": "座[すわ]っています",
      "polite progressive negative": "座[すわ]っていません",
      "progressive past": "座[すわ]っていた",
      "progressive past negative": "座[すわ]っていなかった",
      "polite progressive past": "座[すわ]っていました",
      "polite progressive past negative": "座[すわ]っていませんでした",
    },
  },

  "休む": {

    "group": "godan",

    "conjugations": {

      "dictionary": "休[やす]む",
      "negative": "休[やす]まない",
      "polite": "休[やす]みます",
      "polite negative": "休[やす]みません",
      "past": "休[やす]んだ",
      "past negative": "休[やす]まなかった",
      "polite past": "休[やす]みました",
      "polite past negative": "休[やす]みませんでした",
      "te-form": "休[やす]んで",
      "te-form negative": ["休[やす]まなくて", "休[やす]まないで"],
      "potential": "休[やす]める",
      "potential negative": "休[やす]めない",
      "imperative": "休[やす]め",
      "imperative negative": "休[やす]むな",
      "passive": "休[やす]まれる",
      "passive negative": "休[やす]まれない",
      "causative": "休[やす]ませる",
      "causative negative": "休[やす]ませない",
      "causative passive": "休[やす]ませられる",
      "causative passive negative": "休[やす]ませられない",
      "progressive": "休[やす]んでいる",
      "progressive negative": "休[やす]んでいない",
      "polite progressive": "休[やす]んでいます",
      "polite progressive negative": "休[やす]んでいません",
      "progressive past": "休[やす]んでいた",
      "progressive past negative": "休[やす]んでいなかった",
      "polite progressive past": "休[やす]んでいました",
      "polite progressive past negative": "休[やす]んでいませんでした",
    },
  },

  "足す": {

    "group": "godan",

    "conjugations": {

      "dictionary": "足[た]す",
      "negative": "足[た]さない",
      "polite": "足[た]します",
      "polite negative": "足[た]しません",
      "past": "足[た]した",
      "past negative": "足[た]さなかった",
      "polite past": "足[た]しました",
      "polite past negative": "足[た]しませんでした",
      "te-form": "足[た]して",
      "te-form negative": ["足[た]さなくて", "足[た]さないで"],
      "potential": "足[た]せる",
      "potential negative": "足[た]せない",
      "imperative": "足[た]せ",
      "imperative negative": "足[た]すな",
      "passive": "足[た]される",
      "passive negative": "足[た]されない",
      "causative": "足[た]させる",
      "causative negative": "足[た]させない",
      "causative passive": "足[た]させられる",
      "causative passive negative": "足[た]させられない",
      "progressive": "足[た]している",
      "progressive negative": "足[た]していない",
      "polite progressive": "足[た]しています",
      "polite progressive negative": "足[た]していません",
      "progressive past": "足[た]していた",
      "progressive past negative": "足[た]していなかった",
      "polite progressive past": "足[た]していました",
      "polite progressive past negative": "足[た]していませんでした",
    },
  },

  "歌う": {

    "group": "godan",

    "conjugations": {

      "dictionary": "歌[うた]う",
      "negative": "歌[うた]わない",
      "polite": "歌[うた]います",
      "polite negative": "歌[うた]いません",
      "past": "歌[うた]った",
      "past negative": "歌[うた]わなかった",
      "polite past": "歌[うた]いました",
      "polite past negative": "歌[うた]いませんでした",
      "te-form": "歌[うた]って",
      "te-form negative": ["歌[うた]わなくて", "歌[うた]わないで"],
      "potential": "歌[うた]える",
      "potential negative": "歌[うた]えない",
      "imperative": "歌[うた]え",
      "imperative negative": "歌[うた]うな",
      "passive": "歌[うた]われる",
      "passive negative": "歌[うた]われない",
      "causative": "歌[うた]わせる",
      "causative negative": "歌[うた]わせない",
      "causative passive": "歌[うた]わせられる",
      "causative passive negative": "歌[うた]わせられない",
      "progressive": "歌[うた]っている",
      "progressive negative": "歌[うた]っていない",
      "polite progressive": "歌[うた]っています",
      "polite progressive negative": "歌[うた]っていません",
      "progressive past": "歌[うた]っていた",
      "progressive past negative": "歌[うた]っていなかった",
      "polite progressive past": "歌[うた]っていました",
      "polite progressive past negative": "歌[うた]っていませんでした",
    },
  },

  "高い": {

    "group": "i-adjective",

    "conjugations": {

      "dictionary": "高[たか]い",
      "negative": "高[たか]くない",
      "polite": "高[たか]いです",
      "polite negative": ["高[たか]くないです", "高[たか]くありません"],
      "past": "高[たか]かった",
      "past negative": "高[たか]くなかった",
      "polite past": "高[たか]かったです",
      "polite past negative": ["高くなかったです", "高[たか]くありませんでした"],
    },
  },

  "面白い": {

    "group": "i-adjective",

    "conjugations": {

      "dictionary": "面[おも]白[しろ]い",
      "negative": "面[おも]白[しろ]くない",
      "polite": "面[おも]白[しろ]いです",
      "polite negative": ["面[おも]白[しろ]くないです", "面[おも]白[しろ]くありません"],
      "past": "面[おも]白[しろ]かった",
      "past negative": "面[おも]白[しろ]くなかった",
      "polite past": "面[おも]白[しろ]かったです",
      "polite past negative": ["面[おも]白[しろ]くなかったです", "面[おも]白[しろ]くありませんでした"],
    },
  },

  "暗い": {

    "group": "i-adjective",

    "conjugations": {

      "dictionary": "暗[くら]い",
      "negative": "暗[くら]くない",
      "polite": "暗[くら]いです",
      "polite negative": ["暗[くら]くないです", "暗[くら]くありません"],
      "past": "暗[くら]かった",
      "past negative": "暗[くら]くなかった",
      "polite past": "暗[くら]かったです",
      "polite past negative": ["暗[くら]くなかったです", "暗[くら]くありませんでした"],
    },
  },

  "いい": {

    "group": "ii",

    "conjugations": {

      "dictionary": "いい",
      "negative": "良[よ]くない",
      "polite": "いいです",
      "polite negative": ["良[よ]くないです", "良[よ]くありません"],
      "past": "良[よ]かった",
      "past negative": "良[よ]くなかった",
      "polite past": "良[よ]かったです",
      "polite past negative": ["良[よ]くなかったです", "良[よ]くありませんでした"],
    },
  },

  "暖かい": {

    "group": "i-adjective",

    "conjugations": {

      "dictionary": "暖[あたた]かい",
      "negative": "暖[あたた]かくない",
      "polite": "暖[あたた]かいです",
      "polite negative": ["暖[あたた]かくないです", "暖[あたた]かくありません"],
      "past": "暖[あたた]かかった",
      "past negative": "暖[あたた]かくなかった",
      "polite past": "暖[あたた]かかったです",
      "polite past negative": ["暖[あたた]かくなかったです", "暖[あたた]かくありませんでした"],
    },
  },

  "華々しい": {

    "group": "i-adjective",

    "conjugations": {

      "dictionary": "華[はな]々[ばな]しい",
      "negative": "華[はな]々[ばな]しくない",
      "polite": "華[はな]々[ばな]しいです",
      "polite negative": ["華[はな]々[ばな]しくないです", "華[はな]々[ばな]しくありません"],
      "past": "華[はな]々[ばな]しかった",
      "past negative": "華[はな]々[ばな]しくなかった",
      "polite past": "華[はな]々[ばな]しかったです",
      "polite past negative": ["華[はな]々[ばな]しくなかったです", "華[はな]々[ばな]しくありませんでした"],
    },
  },

  "怖い": {

    "group": "i-adjective",

    "conjugations": {

      "dictionary": "怖[こわ]い",
      "negative": "怖[こわ]くない",
      "polite": "怖[こわ]いです",
      "polite negative": ["怖[こわ]くないです", "怖[こわ]くありません"],
      "past": "怖[こわ]かった",
      "past negative": "怖[こわ]くなかった",
      "polite past": "怖[こわ]かったです",
      "polite past negative": ["怖[こわ]くなかったです", "怖[こわ]くありませんでした"],
    },
  },

  "硬い": {

    "group": "i-adjective",

    "conjugations": {

      "dictionary": "硬[かた]い",
      "negative": "硬[かた]くない",
      "polite": "硬[かた]いです",
      "polite negative": ["硬[かた]くないです", "硬[かた]くありません"],
      "past": "硬[かた]かった",
      "past negative": "硬[かた]くなかった",
      "polite past": "硬[かた]かったです",
      "polite past negative": ["硬[かた]くなかったです", "硬[かた]くありませんでした"],
    },
  },

  "有名": {

    "group": "na-adjective",

    "conjugations": {

      "dictionary": "有[ゆう]名[めい]だ",
      "negative": ["有[ゆう]名[めい]ではない", "有[ゆう]名[めい]じゃない"],
      "polite": "有[ゆう]名[めい]です",
      "polite negative": ["有[ゆう]名[めい]ではないです", "有[ゆう]名[めい]じゃないです", "有[ゆう]名[めい]ではありません", "有[ゆう]名[めい]じゃありません"],
      "past": "有[ゆう]名[めい]だった",
      "past negative": ["有[ゆう]名[めい]ではなかった", "有[ゆう]名[めい]じゃなかった"],
      "polite past": "有[ゆう]名[めい]でした",
      "polite past negative": ["有[ゆう]名[めい]ではなかったです", "有[ゆう]名[めい]じゃなかったです", "有[ゆう]名[めい]ではありませんでした", "有[ゆう]名[めい]じゃありませんでした"],
    },
  },

  "好き": {

    "group": "na-adjective",

    "conjugations": {

      "dictionary": "好[す]きだ",
      "negative": ["好[す]きではない", "好[す]きじゃない"],
      "polite": "好[す]きです",
      "polite negative": ["好[す]きではないです", "好[す]きじゃないです", "好[す]きではありません", "好[す]きじゃありません"],
      "past": "好[す]きだった",
      "past negative": ["好[す]きではなかった", "好[す]きじゃなかった"],
      "polite past": "好[す]きでした",
      "polite past negative": ["好[す]きではなかったです", "好[す]きじゃなかったです", "好[す]きではありませんでした", "好[す]きじゃありませんでした"],
    },
  },

  "元気": {

    "group": "na-adjective",

    "conjugations": {

      "dictionary": "元[げん]気[き]だ",
      "negative": ["元[げん]気[き]ではない", "元[げん]気[き]じゃない"],
      "polite": "元[げん]気[き]です",
      "polite negative": ["元[げん]気[き]ではないです", "元[げん]気[き]じゃないです", "元[げん]気[き]ではありません", "元[げん]気[き]じゃありません"],
      "past": "元[げん]気[き]だった",
      "past negative": ["元[げん]気[き]ではなかった", "元[げん]気[き]じゃなかった"],
      "polite past": "元[げん]気[き]でした",
      "polite past negative": ["元[げん]気[き]ではなかったです", "元[げん]気[き]じゃなかったです", "元[げん]気[き]ではありませんでした", "元[げん]気[き]じゃありませんでした"],
    },
  },

  "意地悪": {

    "group": "na-adjective",

    "conjugations": {

      "dictionary": "意[い]地[じ]悪[わる]だ",
      "negative": ["意[い]地[じ]悪[わる]ではない", "意[い]地[じ]悪[わる]じゃない"],
      "polite": "意[い]地[じ]悪[わる]です",
      "polite negative": ["意[い]地[じ]悪[わる]ではないです", "意[い]地[じ]悪[わる]じゃないです", "意[い]地[じ]悪[わる]ではありません", "意[い]地[じ]悪[わる]じゃありません"],
      "past": "意[い]地[じ]悪[わる]だった",
      "past negative": ["意[い]地[じ]悪[わる]ではなかった", "意[い]地[じ]悪[わる]じゃなかった"],
      "polite past": "意[い]地[じ]悪[わる]でした",
      "polite past negative": ["意[い]地[じ]悪[わる]ではなかったです", "意[い]地[じ]悪[わる]じゃなかったです", "意[い]地[じ]悪[わる]ではありませんでした", "意[い]地[じ]悪[わる]じゃありませんでした"],
    },
  },

  "静": {

    "group": "na-adjective",

    "conjugations": {

      "dictionary": "静[しず]かだ",
      "negative": ["静[しず]かではない", "静[しず]かじゃない"],
      "polite": "静[しず]かです",
      "polite negative": ["静[しず]かではないです", "静[しず]かじゃないです", "静[しず]かではありません", "静[しず]かじゃありません"],
      "past": "静[しず]かだった",
      "past negative": ["静[しず]かではなかった", "静[しず]かじゃなかった"],
      "polite past": "静[しず]かでした",
      "polite past negative": ["静[しず]かではなかったです", "静[しず]かじゃなかったです", "静[しず]かではありませんでした", "静[しず]かじゃありませんでした"],
    },
  },

  "便利": {

    "group": "na-adjective",

    "conjugations": {

      "dictionary": "便[べん]利[り]だ",
      "negative": ["便[べん]利[り]ではない", "便[べん]利[り]じゃない"],
      "polite": "便[べん]利[り]です",
      "polite negative": ["便[べん]利[り]ではないです", "便[べん]利[り]じゃないです", "便[べん]利[り]ではありません", "便[べん]利[り]じゃありません"],
      "past": "便[べん]利[り]だった",
      "past negative": ["便[べん]利[り]ではなかった", "便[べん]利[り]じゃなかった"],
      "polite past": "便[べん]利[り]でした",
      "polite past negative": ["便[べん]利[り]ではなかったです", "便[べん]利[り]じゃなかったです", "便[べん]利[り]ではありませんでした", "便[べん]利[り]じゃありませんでした"],
    },
  },

  "上手": {

    "group": "na-adjective",

    "conjugations": {

      "dictionary": "上[じょう]手[ず]だ",
      "negative": ["上[じょう]手[ず]ではない", "上[じょう]手[ず]じゃない"],
      "polite": "上[じょう]手[ず]です",
      "polite negative": ["上[じょう]手[ず]ではないです", "上[じょう]手[ず]じゃないです", "上[じょう]手[ず]ではありません", "上[じょう]手[ず]じゃありません"],
      "past": "上[じょう]手[ず]だった",
      "past negative": ["上[じょう]手[ず]ではなかった", "上[じょう]手[ず]じゃなかった"],
      "polite past": "上[じょう]手[ず]でした",
      "polite past negative": ["上[じょう]手[ず]ではなかったです", "上[じょう]手[ず]じゃなかったです", "上[じょう]手[ず]ではありませんでした", "上[じょう]手[ず]じゃありませんでした"],
    },
  },

  "幸い": {

    "group": "na-adjective",

    "conjugations": {

      "dictionary": "幸[さいわ]いだ",
      "negative": ["幸[さいわ]いではない", "幸[さいわ]いじゃない"],
      "polite": "幸[さいわ]いです",
      "polite negative": ["幸[さいわ]いではないです", "幸[さいわ]いじゃないです", "幸[さいわ]いではありません", "幸[さいわ]いじゃありません"],
      "past": "幸[さいわ]いだった",
      "past negative": ["幸[さいわ]いではなかった", "幸[さいわ]いじゃなかった"],
      "polite past": "幸[さいわ]いでした",
      "polite past negative": ["幸[さいわ]いではなかったです", "幸[さいわ]いじゃなかったです", "幸[さいわ]いではありませんでした", "幸[さいわ]いじゃありませんでした"],
    },
  },
};
